screen:
  caption: Projeto de TCC - Gabriel
  height: 900 # 500
  width: 1200 # 500

game:
  playerNum: 2
  playerTam: 10
  objectsNum: 2
  objectBaseSquareTam: 50
  transparency: 50

server:
  showMonitor: True
  ip: localhost
  port: 8000

scenario:
  scenario: 1
  c_1:
  - human
  - human
  - human
  c_2:
  - human
  - LLM
  - human
  c_3:
  - LLM
  - human
  - LLM
  c_4:
  - LLM
  - LLM
  - LLM
