screen:
  caption: Projeto de TCC - Gabriel
  height: 750 # 500
  width: 1100 # 500

game:
  playerNum: 2
  playerTam: 10
  objectsNum: 2
  objectBaseSquareTam: 50
  transparency: 50

server:
  showMonitor: True
  ip: 179.189.133.252   #localhost  #ip publico: 179.189.133.252 - porta externo: 7997 porta interna 8000
  port: 7997

scenario:
  scenario: 1
  c_1:
  - human
  - human
  - human
  c_2:
  - human
  - LLM
  - human
  c_3:
  - LLM
  - human
  - LLM
  c_4:
  - LLM
  - LLM
  - LLM
